# GitHub Labels Configuration
# This file defines the comprehensive label system for RouteForceRouting
# Categories: Priority, Type, Status, Component

labels:
  # Priority Labels
  - name: "priority:critical"
    color: "B60205"
    description: "Critical priority - immediate attention required"
  - name: "priority:high"
    color: "D93F0B"
    description: "High priority - should be addressed soon"
  - name: "priority:medium"
    color: "FFA500"
    description: "Medium priority - normal timeline"
  - name: "priority:low"
    color: "FBCA04"
    description: "Low priority - can be addressed later"

  # Type Labels
  - name: "type:bug"
    color: "D73A4A"
    description: "Something isn't working correctly"
  - name: "type:feature"
    color: "0075CA"
    description: "New feature or functionality"
  - name: "type:enhancement"
    color: "A2EEEF"
    description: "Improvement to existing functionality"
  - name: "type:documentation"
    color: "0052CC"
    description: "Documentation updates or improvements"
  - name: "type:security"
    color: "7057FF"
    description: "Security-related issue or improvement"
  - name: "type:performance"
    color: "006B75"
    description: "Performance optimization or issue"
  - name: "type:refactoring"
    color: "5319E7"
    description: "Code refactoring without functional changes"
  - name: "type:maintenance"
    color: "EDEDED"
    description: "Maintenance tasks and dependency updates"

  # Status Labels
  - name: "status:triage"
    color: "FFFFFF"
    description: "Issue needs to be triaged and categorized"
  - name: "status:in-progress"
    color: "F9D0C4"
    description: "Work is currently being done on this issue"
  - name: "status:review"
    color: "0E8A16"
    description: "Ready for code review"
  - name: "status:blocked"
    color: "B60205"
    description: "Cannot proceed due to external dependencies"
  - name: "status:ready-for-merge"
    color: "0E8A16"
    description: "Approved and ready to be merged"
  - name: "status:on-hold"
    color: "FBCA04"
    description: "Work temporarily paused"

  # Component Labels
  - name: "component:backend"
    color: "1D76DB"
    description: "Backend/API related changes"
  - name: "component:frontend"
    color: "0E8A16"
    description: "Frontend/UI related changes"
  - name: "component:mobile"
    color: "FF69B4"
    description: "Mobile app related changes"
  - name: "component:api"
    color: "006B75"
    description: "API design or implementation"
  - name: "component:database"
    color: "8B4513"
    description: "Database schema or queries"
  - name: "component:devops"
    color: "C5DEF5"
    description: "CI/CD, deployment, infrastructure"
  - name: "component:testing"
    color: "F7E018"
    description: "Testing infrastructure or test cases"
  - name: "component:routing"
    color: "FFA500"
    description: "Route optimization algorithms"
  - name: "component:analytics"
    color: "8A2BE2"
    description: "Analytics and monitoring features"

  # Special Labels
  - name: "good-first-issue"
    color: "7057FF"
    description: "Good for newcomers to the project"
  - name: "help-wanted"
    color: "159818"
    description: "Looking for contributors to help with this"
  - name: "duplicate"
    color: "CFD3D7"
    description: "This issue or pull request already exists"
  - name: "wontfix"
    color: "FFFFFF"
    description: "This will not be worked on"
  - name: "question"
    color: "D876E3"
    description: "Further information is requested"

# Legacy labels to remove (if they exist)
remove:
  - "enhancement"  # Replace with type:enhancement
  - "triage"       # Replace with status:triage
  - "high-priority" # Replace with priority:high
  - "medium-priority" # Replace with priority:medium