views:
  - name: "Sprint Board"
    layout: board
    columns:
      - name: "Triage"
        filters:
          - "status:open"
          - "label:status/triage"
      - name: "Ready"
        filters:
          - "status:open" 
          - "label:status/ready"
      - name: "In Progress"
        filters:
          - "status:open"
          - "label:status/in-progress"
      - name: "Review"
        filters:
          - "status:open"
          - "label:status/review"
      - name: "Blocked"
        filters:
          - "status:open"
          - "label:status/blocked"
      - name: "Done"
        filters:
          - "status:closed"
  
  - name: "Priority View"
    layout: table
    columns:
      - field: title
      - field: assignees
      - field: labels
      - field: milestone
    groupBy: priority
    sort:
      - field: priority
        direction: desc
  
  - name: "Component View"
    layout: board
    columns:
      - name: "Routing"
        filters:
          - "status:open"
          - "label:component/routing"
      - name: "UI/Frontend"
        filters:
          - "status:open"
          - "label:component/ui"
      - name: "API/Backend"
        filters:
          - "status:open"
          - "label:component/api"
      - name: "Mobile"
        filters:
          - "status:open"
          - "label:component/mobile"
      - name: "Infrastructure"
        filters:
          - "status:open"
          - "label:component/deployment"