version: "3.9"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URI=postgresql://postgres:postgres@db:5432/routeforce
      - SECRET_KEY=supersecret
      - JWT_SECRET_KEY=jwtsecret
      - SENTRY_DSN=https://bfa8d53ef91ff50ae932cd2f6dcb0f3d@o4509647546286080.ingest.us.sentry.io/4509751159226368
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - rf_net

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: routeforce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - rf_net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - rf_net

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - rf_net

volumes:
  pgdata:
  redis_data:

networks:
  rf_net:
    driver: bridge
