# Netlify deployment configuration for RouteForce
[build]
  publish = "frontend/dist"
  command = "cd frontend && npm run build"

[build.environment]
  VITE_API_BASE_URL = "https://api.routeforcepro.com"
  VITE_ENVIRONMENT = "production"
  VITE_DOMAIN = "app.routeforcepro.com"

# Redirect all requests to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
