# Example Render YAML for advanced deployment configuration
# See: https://render.com/docs/yaml-spec for full options

services:
  - type: web
    name: routeforce-routing
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT --workers 1
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src
