# Render Databases (Managed Services)
databases:
  - name: routeforce-postgres
    databaseName: routeforce
    user: routeforce
    plan: starter
    region: oregon

services:
  # Main Web Service
  - type: web
    name: routeforce-app
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile.production
    region: oregon
    preDeployCommand: ./scripts/run_db_upgrade.sh
    startCommand: "./start_production.sh"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
      - key: PYTHONPATH
        value: /app
      - key: AUTO_COMMIT_ENABLED
        value: "false"
      - key: GIT_AUTO_BACKUP
        value: "false"
      - key: DATABASE_URL
        fromDatabase:
          name: routeforce-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: routeforce-redis
          property: connectionString
      # Keep Sentry DSN managed via Render Dashboard (not synced from repo)
      - key: SENTRY_DSN
        sync: false
      # Keep Flask SECRET_KEY managed via Render Dashboard (not synced from repo)  
      - key: SECRET_KEY
        sync: false
    healthCheckPath: /health
    buildFilter:
      paths:
        - "**"
      ignoredPaths:
        - ".git/**"
        - "node_modules/**"
        - "*.md"
        - ".github/**"
    domains:
      - routeforce-routing.onrender.com
    
  # Redis Cache Service (Render Key Value)
  - type: keyvalue
    name: routeforce-redis
    plan: starter
    region: oregon
    maxmemoryPolicy: noeviction
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all internal connections
    
  # Background Worker (Celery)
  - type: worker
    name: routeforce-worker
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile.production
    region: oregon
    startCommand: "celery -A app.celery_app worker --loglevel=info"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: CELERY_BROKER_URL
        fromService:
          type: keyvalue
          name: routeforce-redis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: routeforce-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: routeforce-redis
          property: connectionString
      # Keep Sentry DSN managed via Render Dashboard (not synced from repo)
      - key: SENTRY_DSN
        sync: false
      # Keep Flask SECRET_KEY managed via Render Dashboard (not synced from repo)
      - key: SECRET_KEY
        sync: false
    buildFilter:
      paths:
        - "**"
      ignoredPaths:
        - ".git/**"
        - "*.md"
        - ".github/**"
