# Example Render YAML for advanced deployment configuration
# See: https://render.com/docs/yaml-spec for full options

services:
  - type: web
    name: routeforce-routing
    runtime: python
    plan: free  # or 'starter', 'standard', etc.
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120"
    envVars:
      - key: FLASK_ENV
        value: production
      # - key: DATABASE_URL
      #   value: your_database_url
      # - key: SECRET_KEY
      #   value: your_secret_key
    autoDeploy: true
    healthCheckPath: /health

# Add additional services (e.g., background workers, cron jobs) as needed.
# For managed databases, set up in Render dashboard and reference the URL above.
