routing/core.py
from routing.route_scoring import rank_routes

def generate_routes(...):  # existing signature
    ...
    # Assume route_candidates is the list of generated routes
    ranked = rank_routes(route_candidates)
    if ranked:
        return ranked[0]["route"]
    return None
