apiVersion: apps/v1
kind: Deployment
metadata:
  name: routeforce-app
  namespace: routeforce
  labels:
    app: routeforce
    component: application
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: routeforce
      component: application
  template:
    metadata:
      labels:
        app: routeforce
        component: application
    spec:
      initContainers:
      - name: migrate
        image: routeforce/app:latest
        command: ["flask", "db", "upgrade"]
        env:
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@routeforce-postgres:5432/$(POSTGRES_DB)"
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: routeforce-config
              key: POSTGRES_USER
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: routeforce-config
              key: POSTGRES_DB
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: routeforce-secrets
              key: POSTGRES_PASSWORD
      containers:
      - name: app
        image: routeforce/app:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          valueFrom:
            configMapKeyRef:
              name: routeforce-config
              key: FLASK_ENV
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@routeforce-postgres:5432/$(POSTGRES_DB)"
        - name: REDIS_URL
          value: "redis://:$(REDIS_PASSWORD)@routeforce-redis:6379/0"
        - name: CACHE_REDIS_URL
          value: "redis://:$(REDIS_PASSWORD)@routeforce-redis:6379/1"
        - name: RATELIMIT_STORAGE_URI
          value: "redis://:$(REDIS_PASSWORD)@routeforce-redis:6379/2"
        - name: CELERY_BROKER_URL
          valueFrom:
            configMapKeyRef:
              name: routeforce-config
              key: CELERY_BROKER_URL
        - name: CELERY_RESULT_BACKEND
          valueFrom:
            configMapKeyRef:
              name: routeforce-config
              key: CELERY_RESULT_BACKEND
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: routeforce-secrets
              key: SECRET_KEY
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: routeforce-secrets
              key: JWT_SECRET_KEY
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: routeforce-config
              key: POSTGRES_USER
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: routeforce-config
              key: POSTGRES_DB
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: routeforce-secrets
              key: POSTGRES_PASSWORD
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: routeforce-secrets
              key: REDIS_PASSWORD
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: uploads
          mountPath: /app/uploads
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: uploads
        emptyDir: {}
      - name: logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: routeforce-app
  namespace: routeforce
  labels:
    app: routeforce
    component: application
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: routeforce
    component: application
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: routeforce-celery-worker
  namespace: routeforce
  labels:
    app: routeforce
    component: celery-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: routeforce
      component: celery-worker
  template:
    metadata:
      labels:
        app: routeforce
        component: celery-worker
    spec:
      containers:
      - name: celery-worker
        image: routeforce/app:latest
        command: ["celery", "-A", "app.celery", "worker", "--loglevel=info", "--concurrency=4"]
        env:
        - name: FLASK_ENV
          valueFrom:
            configMapKeyRef:
              name: routeforce-config
              key: FLASK_ENV
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@routeforce-postgres:5432/$(POSTGRES_DB)"
        - name: REDIS_URL
          value: "redis://:$(REDIS_PASSWORD)@routeforce-redis:6379/0"
        - name: CELERY_BROKER_URL
          value: "redis://:$(REDIS_PASSWORD)@routeforce-redis:6379/3"
        - name: CELERY_RESULT_BACKEND
          value: "redis://:$(REDIS_PASSWORD)@routeforce-redis:6379/4"
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: routeforce-config
              key: POSTGRES_USER
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: routeforce-config
              key: POSTGRES_DB
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: routeforce-secrets
              key: POSTGRES_PASSWORD
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: routeforce-secrets
              key: REDIS_PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: routeforce-celery-beat
  namespace: routeforce
  labels:
    app: routeforce
    component: celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: routeforce
      component: celery-beat
  template:
    metadata:
      labels:
        app: routeforce
        component: celery-beat
    spec:
      containers:
      - name: celery-beat
        image: routeforce/app:latest
        command: ["celery", "-A", "app.celery", "beat", "--loglevel=info"]
        env:
        - name: FLASK_ENV
          valueFrom:
            configMapKeyRef:
              name: routeforce-config
              key: FLASK_ENV
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@routeforce-postgres:5432/$(POSTGRES_DB)"
        - name: REDIS_URL
          value: "redis://:$(REDIS_PASSWORD)@routeforce-redis:6379/0"
        - name: CELERY_BROKER_URL
          value: "redis://:$(REDIS_PASSWORD)@routeforce-redis:6379/3"
        - name: CELERY_RESULT_BACKEND
          value: "redis://:$(REDIS_PASSWORD)@routeforce-redis:6379/4"
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: routeforce-config
              key: POSTGRES_USER
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: routeforce-config
              key: POSTGRES_DB
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: routeforce-secrets
              key: POSTGRES_PASSWORD
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: routeforce-secrets
              key: REDIS_PASSWORD
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "250m"
