name: Bug Report
description: Report a bug or issue with RouteForce
title: "[BUG]: "
labels: ["type:bug", "status:triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide as much detail as possible to help us fix the issue.
  
  - type: input
    id: bug-summary
    attributes:
      label: Bug Summary
      description: Brief description of the bug
      placeholder: ex. Route optimization fails with more than 100 stops
    validations:
      required: true
  
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How severe is this bug?
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true
  
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the system is affected?
      options:
        - Backend
        - Frontend
        - Mobile
        - API
        - Database
        - Routing Algorithm
        - Analytics
        - DevOps
        - Testing
    validations:
      required: true
  
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the bug
      placeholder: |
        1. Go to...
        2. Click on...
        3. Enter...
        4. See error
    validations:
      required: true
  
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should happen instead?
    validations:
      required: true
  
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happens?
    validations:
      required: true
  
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: System information
      placeholder: |
        - OS: [e.g. Windows 10, macOS, Linux]
        - Browser: [e.g. Chrome, Firefox, Safari]
        - Version: [e.g. 1.0.0]
        - Python version: [e.g. 3.9.0]
    validations:
      required: false
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information, screenshots, or logs
    validations:
      required: false