blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/ApacheEcho/RouteForceRouting/discussions
    about: Ask questions, share ideas, and discuss RouteForce Routing with the community
  - name: 📚 Documentation
    url: https://github.com/ApacheEcho/RouteForceRouting/wiki
    about: Read our comprehensive documentation and guides
  - name: 🔒 Security Vulnerabilities
    url: mailto:apacheecho@icloud.com.com
    about: Report security vulnerabilities privately via email
  - name: 💼 Business Inquiries
    url: mailto:apacheecho@icloud.com.com
    about: For business partnerships, licensing, and commercial inquiries
