name: Feature Request
description: Suggest a new feature for RouteForce
title: "[FEATURE]: "
labels: ["type/feature", "status/triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
  
  - type: input
    id: feature-name
    attributes:
      label: Feature Name
      description: Brief name for the feature
      placeholder: ex. Multi-stop route optimization
    validations:
      required: true
  
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - priority/critical
        - priority/high
        - priority/medium
        - priority/low
    validations:
      required: true
  
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component does this feature relate to?
      options:
        - component/routing
        - component/ui
        - component/api
        - component/database
        - component/deployment
        - component/mobile
        - component/analytics
      multiple: true
  
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Detailed description of the feature
    validations:
      required: true