"""Add insights table

Revision ID: fb2a626cc56b
Revises: cbeacf70ea5a
Create Date: 2025-09-02 19:59:55.717054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb2a626cc56b'
down_revision = 'cbeacf70ea5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('insight_type', sa.String(length=80), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.create_index('idx_analytics_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_analytics_event_type', ['event_type'], unique=False)
        batch_op.create_index('idx_analytics_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('route_optimizations', schema=None) as batch_op:
        batch_op.create_index('idx_routeopt_algorithm', ['algorithm'], unique=False)
        batch_op.create_index('idx_routeopt_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_routeopt_route_id', ['route_id'], unique=False)
        batch_op.create_index('idx_routeopt_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.create_index('idx_routes_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_routes_status', ['status'], unique=False)
        batch_op.create_index('idx_routes_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.create_index('idx_stores_chain', ['chain'], unique=False)
        batch_op.create_index('idx_stores_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_stores_is_active', ['is_active'], unique=False)
        batch_op.create_index('idx_stores_name', ['name'], unique=False)
        batch_op.create_index('idx_stores_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_users_email', ['email'], unique=False)
        batch_op.create_index('idx_users_username', ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_username')
        batch_op.drop_index('idx_users_email')
        batch_op.drop_index('idx_users_created_at')

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_index('idx_stores_user_id')
        batch_op.drop_index('idx_stores_name')
        batch_op.drop_index('idx_stores_is_active')
        batch_op.drop_index('idx_stores_created_at')
        batch_op.drop_index('idx_stores_chain')

    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_index('idx_routes_user_id')
        batch_op.drop_index('idx_routes_status')
        batch_op.drop_index('idx_routes_created_at')

    with op.batch_alter_table('route_optimizations', schema=None) as batch_op:
        batch_op.drop_index('idx_routeopt_user_id')
        batch_op.drop_index('idx_routeopt_route_id')
        batch_op.drop_index('idx_routeopt_created_at')
        batch_op.drop_index('idx_routeopt_algorithm')

    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.drop_index('idx_analytics_user_id')
        batch_op.drop_index('idx_analytics_event_type')
        batch_op.drop_index('idx_analytics_created_at')

    op.drop_table('insights')
    # ### end Alembic commands ###
