name: Advanced Project Automation

on:
  issues:
    types: [opened, labeled, unlabeled, assigned]
  issue_comment:
    types: [created]

jobs:
  auto-triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const comment = context.payload.comment;
            
            // Auto-assign based on component labels
            const componentAssignments = {
              'component:backend': 'ApacheEcho',
              'component:frontend': 'frontend-dev',
              'component:api': 'api-team'
            };
            
            // Check for blocking issues
            if (comment && comment.body.includes('blocked by #')) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: ['blocked']
              });
            }
            
            // Auto-prioritize based on keywords
            if (issue.title.toLowerCase().includes('critical') || 
                issue.title.toLowerCase().includes('urgent')) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: ['high-priority']
              });
            }
