name: Dependabot Auto Merge

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test-and-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (or Python, etc.)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Auto-merge Dependabot PR
        if: github.actor == 'dependabot[bot]' && success()
        uses: actions/github-script@v6
        with:
          script: |
            github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              merge_method: 'squash'
            })
