name: Import Issues from CSV

on:
  workflow_dispatch:

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run import script
        run: python import_issues.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}