name: Import Issues from CSV

# This workflow watches for changes to a file named `routeforce_tasks.csv` in the
# repository root. When the file is added or updated on any branch it runs a
# Python script that reads the CSV and creates GitHub issues for each row.
#
# The script uses the GITHUB_TOKEN provided by GitHub Actions to authenticate
# with the GitHub REST API. It supports creating issues with titles, bodies,
# labels and optional assignees defined in the CSV. Failures are logged to
# stdout and to a file named `issue_failures.log` in the repository root.

on:
  push:
    # Only run when the CSV file of interest is created or modified.
    paths:
      - "routeforce_tasks.csv"

jobs:
  import-issues:
    name: Create issues from CSV
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install requests for making HTTP calls to the GitHub API
          pip install requests

      - name: Validate CSV format (optional)
        # Run the CSV validator to ensure required columns exist. The validator
        # will exit with a non‑zero code on failure, which stops the workflow.
        run: python csv_validator.py routeforce_tasks.csv
        continue-on-error: true

      - name: Import issues from CSV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSV_FILE: routeforce_tasks.csv
        run: python import_issues.py