on:
  workflow_dispatch:

jobs:
  scan-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scan Check Placeholder
        run: echo "Scan check workflow placeholder"
