name: Nightly Autobuild

on:
  schedule:
    - cron: "0 3 * * *" # Every night at 3am UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Autobuild
        run: python3 scripts/autobuild.py --autoloop --rank --log --create-next --cleanup
