name: OpenAPI Validate

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Validate OpenAPI parity
        run: |
          python scripts/validate_openapi.py
      - name: Regenerate static openapi.json
        run: |
          python scripts/generate_openapi.py
      - name: Enforce static file up-to-date
        run: |
          git update-index -q --refresh
          if ! git diff --exit-code -- openapi.json; then
            echo "openapi.json is out of date. Run: python scripts/generate_openapi.py and commit the result." >&2
            exit 1
          fi
