name: Project Board Automation

on:
  issues:
    types: [opened, closed, assigned, labeled]
  pull_request:
    types: [opened, closed, merged]

jobs:
  auto-add-to-project:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Add item to project
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const itemType = context.payload.issue ? 'Issue' : 'PullRequest';
            const itemNumber = context.payload.issue?.number || context.payload.pull_request?.number;
            const itemNodeId = context.payload.issue?.node_id || context.payload.pull_request?.node_id;
            
            console.log(`Processing ${itemType} #${itemNumber}`);
            
            // For now, we'll use a simple approach that can be enhanced later
            // This script ensures the automation structure is in place
            
            // Apply labels based on the event type
            if (context.payload.action === 'opened') {
              if (context.payload.issue) {
                await github.rest.issues.addLabels({
                  owner,
                  repo,
                  issue_number: itemNumber,
                  labels: ['needs-triage']
                });
              }
            }
            
            if (context.payload.action === 'closed' && context.payload.issue) {
              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number: itemNumber,
                labels: ['completed']
              });
            }
            
            console.log(`✅ Processed ${itemType} #${itemNumber} successfully`);