# .github/workflows/security.yml
name: Security Scanning

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y

      - name: Scan filesystem with Trivy
        continue-on-error: true
        run: |
          # Scan filesystem but don't fail the workflow on security findings
          trivy fs --no-progress --format sarif --output trivy-results.sarif . || {
            echo "⚠️ Trivy found security issues, but continuing workflow..."
            # Create minimal SARIF file if scan failed completely
            echo '{"version":"2.1.0","runs":[{"tool":{"driver":{"name":"trivy","version":"unknown"}},"results":[]}]}' > trivy-results.sarif
          }

      - name: Check permissions before upload
        run: |
          echo "🔍 Checking upload conditions:"
          echo "Event: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "Repository owner: ${{ github.repository_owner }}"
          
          if [ "${{ github.event_name }}" = "push" ] && [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "✅ Conditions met for SARIF upload"
          else
            echo "ℹ️ SARIF upload will be skipped (not a push to main branch)"
          fi

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        # Only upload on push to main branch to avoid permission issues on forks
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository_owner != 'dependabot[bot]'
        continue-on-error: true
        env:
          CODEQL_ACTION_EXTRA_OPTIONS: '{"database": {"finalize": ["--no-run-unnecessary-builds"]}}'
          CODEQL_DISABLE_TELEMETRY: true
        with:
          sarif_file: trivy-results.sarif
          category: trivy-fs

      - name: Upload Trivy scan results (PR preview)
        if: github.event_name == 'pull_request'
        continue-on-error: true
        run: |
          echo "📄 Trivy scan completed for pull request"
          echo "Results would be uploaded on merge to main branch"
          # Show basic stats
          if [ -f "trivy-results.sarif" ]; then
            echo "SARIF file size: $(wc -c < trivy-results.sarif) bytes"
          fi
