name: Solo Dev Power Automation
on:
  schedule:
    - cron: '55 9 * * *'   # 4:55 AM EST
    - cron: '30 11 * * *'  # 6:30 AM EST  
    - cron: '55 22 * * *'  # 5:55 PM EST
    - cron: '0 1 * * *'    # 8:00 PM EST
  push:
  workflow_dispatch:

jobs:
  morning-prep:
    if: contains(github.event.schedule, '55 9')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Morning Prep
        run: echo "🌅 Workspace ready for 5 AM EST!"
