name: Stale Issue Management

on:
  schedule:
    - cron: "0 1 * * *"  # Run daily at 1 AM UTC
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: |
            This issue has been automatically marked as stale because it has not had recent activity. 
            It will be closed if no further activity occurs. Thank you for your contributions.
            
            If this issue is still relevant, please:
            - Add a comment to keep it open
            - Add the `keep-open` label to prevent auto-closure
            - Update the issue with current status
          stale-pr-message: |
            This pull request has been automatically marked as stale because it has not had recent activity.
            It will be closed if no further activity occurs. Thank you for your contributions.
            
            If this PR is still relevant, please:
            - Add a comment to keep it open  
            - Rebase on the latest main branch
            - Request a review if ready
          close-issue-message: |
            This issue was closed because it has been stale for 30 days with no activity.
            Feel free to reopen if this is still relevant.
          close-pr-message: |
            This pull request was closed because it has been stale for 14 days with no activity.
            Feel free to reopen if you want to continue working on this.
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          exempt-issue-labels: 'keep-open,high-priority,security,blocked,pinned'
          exempt-pr-labels: 'keep-open,high-priority,security,blocked,pinned'
          days-before-issue-stale: 60
          days-before-pr-stale: 30
          days-before-issue-close: 30
          days-before-pr-close: 14
          operations-per-run: 100